name: Pull Request

on:
  pull_request:
    paths-ignore:
      - '*.md'

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Needed so tags are fetched

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build catalog
        run: ./gradlew generateCatalogAsToml

      - name: Store hprof files
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: hprofs
          path: ./**/*.hprof
      - name: Store daemon log
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: daemon-log
          path: ./**/*.out.log
      - name: Store gc logs
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: gc-logs
          path: ./**/build/gc/*.log
