name: Pre-merge

on:
  pull_request:
  merge_group:

jobs:
  build:
    uses: kyhule/polyworld-workflows/.github/workflows/pre-merge.yml@a26f05dbaa65b38aef88fd576709fdce64059d07
    secrets: inherit
    with:
      setup-android: false
      build-tasks: 'generateCatalogAsToml'
