name: Pre-merge

on:
  pull_request:
  merge_group:

jobs:
  build:
    uses: kyhule/polyworld-workflows/.github/workflows/pre-merge.yml@f0a535faadb2aafdd961219125457f01ad2964f1
    secrets: inherit
    with:
      setup-android: false
      build-tasks: 'generateCatalogAsToml'
